### ISSUE TITLE
Add the "Problem Statement" for the project in a Wiki Page.

### ISSUE THREAD

**Issue by dbc2201** [dbc2201/TripWhiz#1]
- [x] Create a new [Wiki](https://docs.github.com/en/github/building-a-strong-community/about-wikis) page for the problem statement.

**Comment by cybertronayush** [comment]
[https://github.com/dbc2201/TripWhiz/wiki/Problem-Statement](url)

**Comment by dbc2201** [comment]
Please do not close the issues yourself, I will check the task and do it.

**Comment by cybertronayush** [comment]
Okay, Sir, I will keep this in mind in the future.
